### ISSUE TITLE
Unexpected error fetching multimatic_facility_detail

### ISSUE THREAD

**Issue by erikleirdal** [thomasgermain/vaillant-component#108]
Hey. Any idea why i got this issue trying to integrate  the valliant VR920 for HA for the first time?

This error originated from a custom integration.

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:86
Integration: Multimatic (documentation, issues)
First occurred: 8:38:30 PM (1 occurrences)
Last logged: 8:38:30 PM

Unexpected error fetching multimatic_facility_detail data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 520, in _first_fetch_data
    result = await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 509, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 86, in get_facility_detail
    detail = await self._manager.get_facility_detail(self.serial)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 245, in get_facility_detail
    return mapper.map_facility_detail(
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 249, in map_facility_detail
    facility = [
IndexError: list index out of range

**Comment by erikleirdal** [comment]
wrong serial# :)
case closed - working perfectly now.
