### ISSUE TITLE
Vaillant server problem?

### ISSUE THREAD

**Issue by johanvh83** [thomasgermain/vaillant-component#111]
HA OS Core: 2021.12.08
Home Assistant OS 7.1
Multimatic: 1.12.1

Today between 16:39 and 17:04 I have no data for many sensors like sensor.domestichotwatertanktemperature, sensor.flowtemperaturesensor and others.
At 17:02 an automation to set the temperature in 2 rooms run, but the temperature wasn't changed.
Around 17:30 I run the automation manually and it worked.
My log shows:
This error originated from a custom integration.

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:104
Integration: Multimatic (documentation, issues)
First occurred: 4:39:32 PM (12 occurrences)
Last logged: 5:02:05 PM

Unexpected error fetching multimatic_rooms data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 516, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 509, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 104, in get_rooms
    return await self._manager.get_rooms()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 336, in get_rooms
    rooms = await self._call_api(urls.rooms, schema=schemas.ROOM_LIST)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
    raise ex
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 844, in _call_api
    await self._ensure_ready()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 878, in _ensure_ready
    await self._connector.login()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 66, in login
    token = await self._token()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 109, in _token
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None

I think the Vaillant server was offline at that time. Is that a correct conclusion?

**Comment by thomasgermain** [comment]
Yes same here. Status 503 means there is something wrong at server side. If you try the app, you will have an error message

**Comment by johanvh83** [comment]
I was not at home, so I couldn't try at that time but was wondering why the automation hadn't worked...
Thanks.
