### ISSUE TITLE
Vaillant server offline but 'binary_sensor_multimatic_system_online' shows 'online'

### ISSUE THREAD

**Issue by johanvh83** [thomasgermain/vaillant-component#112]
Hi,

This morning, again, I couldn't connect. Tried the multiMATIC app and same problem: couldn't connect.
It's strange that the binary sensor multimatic_system_online_serial number has the status 'online' while it's clear the server is offline. Do you have any chance to change your code in order to have a realistic reading of this 'system online' status?

The log shows:

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/multimatic/binary_sensor.py:214
Integration: Multimatic (documentation, issues)
First occurred: January 20, 2022, 11:41:38 AM (2 occurrences)
Last logged: January 20, 2022, 5:41:52 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    if (name := (entry and entry.name) or self.name) is not None:
  File "/config/custom_components/multimatic/binary_sensor.py", line 214, in name
    return f"{self.device.name} {self.device_class}"
AttributeError: 'NoneType' object has no attribute 'name'
`
and

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/multimatic/binary_sensor.py:110
Integration: Multimatic (documentation, issues)
First occurred: January 20, 2022, 11:41:33 AM (3 occurrences)
Last logged: January 20, 2022, 5:41:48 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    if (name := (entry and entry.name) or self.name) is not None:
  File "/config/custom_components/multimatic/binary_sensor.py", line 110, in name
    return self.coordinator.data.circulation.name
AttributeError: 'NoneType' object has no attribute 'circulation'
`
and

`This error originated from a custom integration.

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:118
Integration: Multimatic (documentation, issues)
First occurred: January 20, 2022, 1:17:47 PM (1 occurrences)
Last logged: January 20, 2022, 1:17:47 PM

Unexpected error fetching multimatic_dhw data: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 516, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 509, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 118, in get_dhw
    dhw = await self._manager.get_dhw()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 327, in get_dhw
    return mapper.map_dhw(dhw)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 427, in map_dhw
    hotwater = map_hot_water_from_dhw(dhw)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 406, in map_hot_water_from_dhw
    return _map_hot_water(dhw.get("hotwater"), dhw_id, None)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 540, in _map_hot_water
    timep, mode, high, low = _map_function(raw_hot_water, "mode")
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 371, in _map_function
    operating_mode = OperatingModes.get(mode)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mode.py", line 82, in get
    return cls._VALUES[name]
KeyError: None
`

`This error originated from a custom integration.

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:118
Integration: Multimatic (documentation, issues)
First occurred: January 20, 2022, 7:17:30 AM (1 occurrences)
Last logged: January 20, 2022, 7:17:30 AM

Unexpected error fetching multimatic_dhw data: Unable to authenticate at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 516, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 509, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 118, in get_dhw
    dhw = await self._manager.get_dhw()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 326, in get_dhw
    dhw = await self._call_api(urls.dhws, schema=schemas.DHWS)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 857, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 157, in request
    await self.login(True)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 67, in login
    await self._authenticate(token)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 125, in _authenticate
    raise ApiError(
pymultimatic.api.error.ApiError: Unable to authenticate at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None`

**Comment by thomasgermain** [comment]
Hello,

there is 3 things here:
- the server is online since you receive an HTTP 401 (if it was offline, you wouldn't receive any response)
- the binary sensor tells you if *your* system is online. You should be able to make to binary sensor turn off if you unplug your VR9XX box.
- The state binary sensor only rely on what the API sends, so if it says it's online, I can only trust it.

**Comment by johanvh83** [comment]
Thanks Thomas,

I agree, the server was online but it couldn't handle the authentication. Would't it be an idea to create an own 'online' status based on HA logs, I guess they are outputted from your respo, instead of using the API from Vaillant?

**Comment by thomasgermain** [comment]
Yes, the integration is creating logs entries, but to me this is outside the scope of the integratio.

Maybe you can use a command line sensor like grep and tail to check if there is some errors related to multimatic integration
