### ISSUE TITLE
Unable to authenticate at https://smart.vaillant... [401 NOT_AUTHORIZED]

### ISSUE THREAD

**Issue by meironke** [thomasgermain/vaillant-component#118]
Hey Thomas,

**THANK YOU** for this integration. It **saves me real money** since I can control my heating!

My issue:
- The integration works quite well. I am (generally) authenticated, get all data points and can send service calls against the system
- But the connection to the Vaillant system is not stable
- I get 401 errors NOT_AUTHORIZED (~5-6 times per hour)
- Sensor data then is "unavailable"
- After reconnecting properly everything works smoothly until the next reconnect
- You can see the reconnects in the history of one sensor history
- The issue does apply to all connected devices 
- The multiMATIC app on my phone works well, no AUTH issues there

My setup:
- Home Assistant 2022.2.1 
- Vaillant multiMATIC v3.9.3 
- VR921 FW 357.24.2

**Do you have any idea how to fix this?**

Thanks a lot!
Ingo

### Sensor History displaying disconnects
![Vaillant-Sensor-History](https://user-images.githubusercontent.com/56265223/152676569-e5cfdcd6-c16b-4ca2-9b85-ec4ba8bc6654.png)

### Disconnects of all devices
![Vaillant-Reconnects](https://user-images.githubusercontent.com/56265223/152676616-e6382a25-3c57-40d9-bae4-79200c2bae9d.png)

### Log entry of one issue
```
Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:99
Integration: Multimatic ([documentation](https://github.com/thomasgermain/vaillant-component), [issues](https://github.com/thomasgermain/vaillant-component/issues))
First occurred: 10:55:44 (1 occurrences)
Last logged: 10:55:44

Unexpected error fetching multimatic_outdoor_temperature data: Unable to authenticate at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 516, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 509, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 99, in get_outdoor_temperature
    return await self._manager.get_outdoor_temperature()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 227, in get_outdoor_temperature
    return mapper.map_outdoor_temp(await self._call_api(urls.system_status))
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 857, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 157, in request
    await self.login(True)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 67, in login
    await self._authenticate(token)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 125, in _authenticate
    raise ApiError(
pymultimatic.api.error.ApiError: Unable to authenticate at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/authenticate, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None
```

**Comment by thomasgermain** [comment]
Hello,

Are you using a dedicated user for the integration ?

**Comment by meironke** [comment]
Yes, I did - a dedicated user for Home Assistant
