### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by mgmtotorsperformance** [thomasgermain/vaillant-component#122]
After latest update integration stopped workig

Deleted it and tried to install again 
When im trying to add Multimatic integration is shows me 500 Internal Server Error Server got itself in trouble

log
Logger: aiohttp.server
Source: requirements.py:180
First occurred: 20:29:10 (1 occurrences)
Last logged: 20:29:10

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 134, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 221, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 740, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 352, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
    await _async_process_integration(hass, integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in _async_process_integration
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 162, in async_process_requirements
    await _async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 180, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for multimatic not found: ['pymultimatic==0.6.6'].

Any help? It was working perfect untill last core-2022.3.0b1 installed.

Thanks
MG

**Comment by thomasgermain** [comment]
Hello,

this is quite strange, I just checked, and 0.6.6 version is there in pypi: https://pypi.org/project/pymultiMATIC/

I also check the release for the next beta and there is nothing mentioned about the pypi dependencies.

Could you test with the last beta ?

**Comment by thomasgermain** [comment]
Oh, found it:

```
The conflict is caused by:
    pymultimatic 0.6.6 depends on aiohttp==3.7.4.post0
    The user requested (constraint) aiohttp==3.8.1
```

I'll work on it, I need to release pymultimatic and the integration

**Comment by thomasgermain** [comment]
Just released https://github.com/thomasgermain/vaillant-component/releases/tag/1.12.3, it should fix the issue.

Could you confirm ?

**Comment by mgmtotorsperformance** [comment]
working fine

In app i can control recuperation (Ventilation) as well 
I cant see ventilation on HA integration? Can this be added?

**Comment by thomasgermain** [comment]
I'm glad it's working !

Could you create another issue for the ventilation ? Normally you should be able to control it via a fan entity.
