### ISSUE TITLE
Cooling not supported?

### ISSUE THREAD

**Issue by switschel** [thomasgermain/vaillant-component#133]
Hi I just tried for testing purpose to set my multimatic to "cooling" using HA.
I got the following error:
[140023989430208] Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21200500202609650938006303N3/systemcontrol/v1/configuration/quickmode, status: 400, response: {"errorCode":"INVALID_PARAMS"},payload: {'quickmode': {'quickmode': 'QM_COOLING_FOR_X_DAYS'}}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/multimatic/climate.py", line 499, in async_set_hvac_mode
    await self.coordinator.api.set_zone_operating_mode(self, mode)
  File "/config/custom_components/multimatic/coordinator.py", line 304, in set_zone_operating_mode
    await self._manager.set_quick_mode(mode)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 405, in set_quick_mode
    await self._call_api(
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 857, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 164, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21200500202609650938006303N3/systemcontrol/v1/configuration/quickmode, status: 400, response: {"errorCode":"INVALID_PARAMS"},payload: {'quickmode': {'quickmode': 'QM_COOLING_FOR_X_DAYS'}}

**Comment by thomasgermain** [comment]
Hello,

which version of HA and component are you using ?
Did you call the `set_quick_mode` service ?

Sounds like you called the service with  `quick_mode` parameter but without the `duration`

**Comment by thomasgermain** [comment]
Ah, I didn't know I allowed that :sweat_smile:

I will provide a fix to handle that. In the meantime, you can directly call `set_quick_mode` service with `QM_COOLING_FOR_X_DAYS` quick_mode and you should specify a duration. (in day)

**Comment by switschel** [comment]
@thomasgermain It is working fine now. Thanks for the fast fix!
