### ISSUE TITLE
Some entities unavailable

### ISSUE THREAD

**Issue by Woempia** [thomasgermain/vaillant-component#137]
Hi

I have some entities that always appear as unavailable. Any way to solve this?

I do have the data available in multimatic app

![Screenshot_20220606-202605_Home Assistant](https://user-images.githubusercontent.com/99049720/172223431-acecb094-b65c-4bfa-98b9-0645c5c5a621.jpg)
![Screenshot_20220606-202542_Home Assistant](https://user-images.githubusercontent.com/99049720/172223435-88e8c8ef-de3f-4034-b988-6b6c053f34ff.jpg)

**Comment by thomasgermain** [comment]
Hello, 
Do you have any errors in the log ?

**Comment by Woempia** [comment]
I get this message

![Screenshot_20220614-213614_Home Assistant](https://user-images.githubusercontent.com/99049720/173673985-dcab18f0-3989-44ba-b7b3-a0b214830f89.jpg)


These are the logs I can find but not sure if relevant 

This error originated from a custom integration.

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:94
Integration: Multimatic (documentation, issues)
First occurred: June 11, 2022, 4:00:49 PM (34 occurrences)
Last logged: 9:26:49 PM

Unexpected error fetching multimatic_zones data: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 533, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 526, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 94, in get_zones
    return await self._manager.get_zones()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 362, in get_zones
    return mapper.map_zones(rooms)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 265, in map_zones
    return _map_zones(json.get("body", []))
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 277, in _map_zones
    zone = map_zone(raw_zone)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 306, in map_zone
    func = _map_function(raw_heating, "setting", rbr, quick_veto is not None)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mapper.py", line 371, in _map_function
    operating_mode = OperatingModes.get(mode)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/model/mode.py", line 82, in get
    return cls._VALUES[name]
KeyError: None


Logger: homeassistant.core
Source: core.py:1583
First occurred: 9:24:47 PM (2 occurrences)
Last logged: 9:24:47 PM

Unable to remove unknown service multimatic/set_ventilation_night_level
Unable to remove unknown service multimatic/set_ventilation_day_level




This error originated from a custom integration.

Logger: custom_components.multimatic.coordinator
Source: helpers/update_coordinator.py:204
Integration: Multimatic (documentation, issues)
First occurred: June 13, 2022, 6:03:26 PM (27 occurrences)
Last logged: 8:29:32 PM

Error requesting multimatic_zones data: [Errno 104] Connection reset by peer
Error requesting multimatic_hvac_status data: [Errno 104] Connection reset by peer
Error requesting multimatic_quick_mode data: [Errno 104] Connection reset by peer
Error requesting multimatic_dhw data: [Errno 104] Connection reset by peer
Error requesting multimatic_quick_mode data: Cannot connect to host smart.vaillant.com:443 ssl:default [Connect call failed ('195.179.164.64', 443)]

**Comment by thomasgermain** [comment]
This is something I can't do about it :/ the server is quite unstable at vaillant side.
