### ISSUE TITLE
Entities and sensors blank - Cannot get token - 503 Service Unavailable

### ISSUE THREAD

**Issue by Wiggum127** [thomasgermain/vaillant-component#138]
I've been witnessing an persistant issue with the integration the last week. While everything has been functioning correctly for months in a row, since about at least a week, all sensors or info from the integration are blank.

The Vaillant native app on Android works fine and shows correct readinds and up to date info.

Have done an update of the HA Docker instance and restarted already a few times, but the behaviour persists.

A few error which might be helpfull to debug:

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:135
Integration: Multimatic (documentation, issues)
First occurred: 13 juni 2022 22:47:16 (52 occurrences)
Last logged: 04:59:32

Unexpected error fetching multimatic_quick_mode data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
return await self.update_method()
File "/config/custom_components/multimatic/coordinator.py", line 537, in _first_fetch_data
result = await self._fetch_data()
File "/config/custom_components/multimatic/coordinator.py", line 526, in _fetch_data
return await getattr(self.api, self._method)()
File "/config/custom_components/multimatic/coordinator.py", line 135, in get_quick_mode
self._quick_mode = await self._manager.get_quick_mode()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 302, in get_quick_mode
return mapper.map_quick_mode(await self._call_api(urls.system_quickmode))
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
raise ex
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 844, in _call_api
await self._ensure_ready()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 878, in _ensure_ready
await self._connector.login()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 66, in login
token = await self._token()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 109, in _token
raise ApiError(
pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None

--

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:135
Integration: Multimatic (documentation, issues)
First occurred: 14 juni 2022 00:09:06 (3 occurrences)
Last logged: 15 juni 2022 04:55:00

Unexpected error fetching multimatic_quick_mode data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21203000202529220938020806N8/systemcontrol/v1/configuration/quickmode, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
return await self.update_method()
File "/config/custom_components/multimatic/coordinator.py", line 533, in _fetch_data_if_needed
return await self._fetch_data()
File "/config/custom_components/multimatic/coordinator.py", line 526, in _fetch_data
return await getattr(self.api, self._method)()
File "/config/custom_components/multimatic/coordinator.py", line 135, in get_quick_mode
self._quick_mode = await self._manager.get_quick_mode()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 302, in get_quick_mode
return mapper.map_quick_mode(await self._call_api(urls.system_quickmode))
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
raise ex
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 857, in _call_api
response = await self._connector.request(method, url, payload)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 164, in request
raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21203000202529220938020806N8/systemcontrol/v1/configuration/quickmode, status: 503, response: Service Unavailable,payload: None

--

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:152
Integration: Multimatic (documentation, issues)
First occurred: 13 juni 2022 22:47:40 (1 occurrences)
Last logged: 13 juni 2022 22:47:40

Unexpected error fetching multimatic_emf_reports data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
return await self.update_method()
File "/config/custom_components/multimatic/coordinator.py", line 537, in _first_fetch_data
result = await self._fetch_data()
File "/config/custom_components/multimatic/coordinator.py", line 526, in _fetch_data
return await getattr(self.api, self._method)()
File "/config/custom_components/multimatic/coordinator.py", line 152, in get_emf_reports
return await self._manager.get_emf_devices()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 210, in get_emf_devices
return mapper.map_emf_reports(await self._call_api(urls.emf_devices))
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
raise ex
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 844, in _call_api
await self._ensure_ready()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 878, in _ensure_ready
await self._connector.login()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 66, in login
token = await self._token()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 109, in _token
raise ApiError(
pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None

**Comment by thomasgermain** [comment]
I can't do anything about that, the server returns an HTTP 503 error: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

**Comment by Wiggum127** [comment]
I imagined you would be interested in seeing the error log and how the integration is dealing with this error.

In the meantime I established a fix/workaround: re-download the integration and restarting HA fixed the issue for me.

As this fixed the issue, it's probable also on the client side. Outdated token, perhaps ?

**Comment by Wiggum127** [comment]
So if it is only server related, how would reloading the integration fix this problem?
Is some initialisation only happening at startup which can be repeated at client side when a 503 is received? That would avoid the need of having to do a full reload and reboot of HA just to get things working again.
