### ISSUE TITLE
HA 2023.01 / Requirements for multimatic not found

### ISSUE THREAD

**Issue by Strohhutpat** [thomasgermain/vaillant-component#177]
It's look like, multimatic is needing an update for HA 2023.01 

Setup failed for custom integration multimatic: Requirements for multimatic not found: ['pymultimatic==0.6.11'].

Unable to install package pymultimatic==0.6.11: ERROR: Cannot install pymultimatic==0.6.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by thomasgermain** [comment]
Thanks for spotting it.

Release note doesn't mention it :/

**Comment by thomasgermain** [comment]
Version https://github.com/thomasgermain/vaillant-component/tree/1.12.12 should be compatible :)

**Comment by Strohhutpat** [comment]
Can't download

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:877
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:10:37 (1 occurrences)
Last logged: 19:10:37

[546718915392] Error handling message: Unknown error (unknown_error) from 127.0.0.1 (Mozilla/5.0 (Linux; Android XX; XXX Build/58.2.A.10.126; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 Home Assistant/2022.12.0-3026 (Android 12; XQ-AS52))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 216, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 837, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 877, in async_install_repository
    raise HacsException("The version of Home Assistant is not compatible with this version")
custom_components.hacs.exceptions.HacsException: The version of Home Assistant is not compatible with this version

**Comment by thomasgermain** [comment]
Yeah, it sounds like lastest version is `2023.1.0b3` which actually doesn't meet the minimal requirement `2023.1.0`.

I guess you will have to wait for the official release, or install it manually

**Comment by Strohhutpat** [comment]
Fix works for me
