### ISSUE TITLE
Multimatic error

### ISSUE THREAD

**Issue by colesadam** [thomasgermain/vaillant-component#181]
Hi, seeing a lot of this in the logs, 
```
Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:94
Integration: Multimatic ([documentation](https://github.com/thomasgermain/vaillant-component), [issues](https://github.com/thomasgermain/vaillant-component/issues))
First occurred: 01:50:58 (61 occurrences)
Last logged: 11:32:00

Unexpected error fetching multimatic_zones data: None
```
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 537, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 530, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 94, in get_zones
    return await self._manager.get_zones()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 362, in get_zones
    return mapper.map_zones(rooms)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/model/mapper.py", line 265, in map_zones
    return _map_zones(json.get("body", []))
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/model/mapper.py", line 277, in _map_zones
    zone = map_zone(raw_zone)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/model/mapper.py", line 306, in map_zone
    func = _map_function(raw_heating, "setting", rbr, quick_veto is not None)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/model/mapper.py", line 371, in _map_function
    operating_mode = OperatingModes.get(mode)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/model/mode.py", line 82, in get
    return cls._VALUES[name]
KeyError: None`

Seems to be mostly around heating, other sensors are still returning data

**Comment by thomasgermain** [comment]
Hello,

this is something happening time to time. The API return a response, but incomplete. The connector and the integration can deal with incomplete response but with some limitation. In your case, the API return a response for a zone, but there is no information about the operating mode the zone is running, which is mandatory for HA (because the state is based on this operating mode).
