### ISSUE TITLE
Loosing connection and access to Vaillaint

### ISSUE THREAD

**Issue by bartverckens** [thomasgermain/vaillant-component#186]
Hi,
currently I'm facing the issue that after some hours/few days I'm loosing my access to the Multimatic app as well as in the HA Vaillant integration. Already twice I had to contact valliant support to get my account reset ( resulting each time I need to create new username link to my VR912 serial). This is also happening when I created multiple users access in the Multimatic app and have HA en the app use different users. Integration is working for couple of hours max few days.

**Comment by bartverckens** [comment]
in the log I have:
Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:135 
Integration: Multimatic ([documentation](https://github.com/thomasgermain/vaillant-component), [issues](https://github.com/thomasgermain/vaillant-component/issues)) 
First occurred: 19:59:40 (4 occurrences) 
Last logged: 20:14:41

Unexpected error fetching multimatic_quick_mode data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 542, in _first_fetch_data
    result = await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 530, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 135, in get_quick_mode
    self._quick_mode = await self._manager.get_quick_mode()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 302, in get_quick_mode
    return mapper.map_quick_mode(await self._call_api(urls.system_quickmode))
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 854, in _call_api
    await self._ensure_ready()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 888, in _ensure_ready
    await self._connector.login()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 71, in login
    token = await self._token()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 114, in _token
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None

**Comment by bartverckens** [comment]
also found this warning:
Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:162 
Integration: Multimatic ([documentation](https://github.com/thomasgermain/vaillant-component), [issues](https://github.com/thomasgermain/vaillant-component/issues)) 
First occurred: 20:05:26 (1 occurrences) 
Last logged: 20:05:26

Request_hvac_update is done too often
Traceback (most recent call last):
  File "/config/custom_components/multimatic/coordinator.py", line 162, in request_hvac_update
    await self._manager.request_hvac_update()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 820, in request_hvac_update
    state = mapper.map_hvac_sync_state(await self._call_api(urls.hvac))
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 854, in _call_api
    await self._ensure_ready()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 888, in _ensure_ready
    await self._connector.login()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 71, in login
    token = await self._token()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 114, in _token
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 401, response: {"errorCode":"NOT_AUTHORIZED"},payload: None

**Comment by thomasgermain** [comment]
Hello,

are you using a different user for HA ? Vaillant API doesn't like same user to be connected twice to the API

**Comment by bartverckens** [comment]
Hi,
yes. They have reset it again at Valiant side. Created again a second account via the multimatic app and added this user in the HA integration now again. Now wait and see. They did confirm there is no polling limit but I have set the time to 5minutes en disables all men related automations

**Comment by thomasgermain** [comment]
Hello,
Are you using the latest version of the integration ?

I'm polling every minute and I don't have any issue.

**Comment by bartverckens** [comment]
Yes, Im now on 1.13

**Comment by mikyD84** [comment]
i got the same issue, 

after install all was working fine, after 10min lost connection. 
the app is also offline mybe server problem? 

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:152
Integration: Multimatic (documentation, issues)
First occurred: 22:07:29 (2 occurrences)
Last logged: 22:17:48

Unexpected error fetching multimatic_emf_reports data: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 542, in _first_fetch_data
    result = await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 530, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 152, in get_emf_reports
    return await self._manager.get_emf_devices()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 210, in get_emf_devices
    return mapper.map_emf_reports(await self._call_api(urls.emf_devices))
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
    raise ex
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 854, in _call_api
    await self._ensure_ready()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 888, in _ensure_ready
    await self._connector.login()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 71, in login
    token = await self._token()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 114, in _token
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get token at https://smart.vaillant.com/mobile/api/v4/account/authentication/v1/token/new, status: 503, response: Service Unavailable,payload: None

**Comment by bartverckens** [comment]
Hi,
this issue can be closed. Since last reset by Vaillant and blocked my automations the access remains stable with minor disconnects when checking the online status. Thus although they confirm there is no limit, due too frequent actions via my automation I did force them to have my account blocked.  Reviewing my automations now.
