### ISSUE TITLE
Not able to configure/set up integration

### ISSUE THREAD

**Issue by Kaot93** [thomasgermain/vaillant-component#188]
I get this error trying to set up the integration: 

```This error originated from a custom integration.

Logger: custom_components.multimatic.config_flow
Source: custom_components/multimatic/config_flow.py:43
Integration: Multimatic (documentation, issues)
First occurred: 22:21:54 (3 occurrences)
Last logged: 23:13:42

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/multimatic/config_flow.py", line 74, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/multimatic/config_flow.py", line 35, in validate_input
    await validate_authentication(hass, data[CONF_USERNAME], data[CONF_PASSWORD])
  File "/config/custom_components/multimatic/config_flow.py", line 43, in validate_authentication
    if not await SystemManager(
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 146, in login
    return await self._connector.login(force_login)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 71, in login
    token = await self._token()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 110, in _token
    token_res = await self._session.post(url=urls.new_token(), json=params, headers=HEADER)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host smart.vaillant.com:443 ssl:default [Name does not resolve]```

**Comment by thomasgermain** [comment]
Are you using some kind of custom DNS ? It sounds like smart.vaiilant.com cannot be resolved

**Comment by Kaot93** [comment]
Nope, no DNS. 

I read that it couldn't be resolved and tried to manually access it - which worked as expected.

**Comment by Kaot93** [comment]
Is there a way I could debug this? 
I tried a `curl google.com` which worked, so it may be not a general problem with my HA. 

I have HA running as a VM in proxmox, if that matters.

**Comment by Kaot93** [comment]
So I dug a lot into the DNS stuff and somehow managed to solve this issue. I don't know exactly what really solved the issue, but I got the integration set up.
