### ISSUE TITLE
Error when trying to set quick veto 

### ISSUE THREAD

**Issue by Kaot93** [thomasgermain/vaillant-component#196]
I attached a log of my try to set a quick veto. The comment got rejected.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/multimatic/coordinator.py:249
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:27:46 (3 occurrences)
Last logged: 23:28:12

[140171337338112] Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21170700201971450933007058N0/systemcontrol/v1/zones/Control_ZO2/configuration/quick_veto, status: 409, response: {"errorCode":"COMMAND_REJECTED"},payload: {'setpoint_temperature': 16.0}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 198, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/multimatic/climate.py", line 494, in async_set_temperature
    await self.coordinator.api.set_zone_target_temperature(self, temp)
  File "/config/custom_components/multimatic/coordinator.py", line 249, in set_zone_target_temperature
    await self._manager.set_zone_quick_veto(zone.id, veto)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 631, in set_zone_quick_veto
    await self._call_api(self.urls.zone_quick_veto, params={"id": zone_id}, payload=payload)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 894, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 171, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21170700201971450933007058N0/systemcontrol/v1/zones/Control_ZO2/configuration/quick_veto, status: 409, response: {"errorCode":"COMMAND_REJECTED"},payload: {'setpoint_temperature': 16.0}
```

**Comment by thomasgermain** [comment]
First time I see this error :/

Are you able to reproduce ? 
Did you have any quick mode set when trying the set the quick veto for the zone ?
Are you able to set a quick veto through the mobile app for this zone ?
