### ISSUE TITLE
VR921 - Senso App - No Climate Entity

### ISSUE THREAD

**Issue by CommanderROR9** [thomasgermain/vaillant-component#203]
Hi,

I installed the integration yesterday and had a "Climate Entity" at first. However, this became inactive and disappeared completely after reading the integration. I am running the latest beta and while I can see all the data,I cannot change anything (no quick modes etc) and I also can't set the temperature at all (or even see it) since the Climate entity is missing entirely.

Any clues why it was there initially and now vanished?

**Comment by thomasgermain** [comment]
Hello,

Did you select sensoAPP check box while adding the integration ?
Do you have any errors in the logs ?

**Comment by CommanderROR9** [comment]
I did select Senso App during Setup (multimatic gives me 0 entities, I tried that later). 
And no, not seeing any obvious errors related to the integration. I will turn on more in-depth logging and see if something shows up.

**Comment by thomasgermain** [comment]
@xaviergriffon mind you have a look please ? Since this is senso, I'm limited in the debug, thanks 😊

**Comment by CommanderROR9** [comment]
A short snippet from the debug log. Seems the integration is throwing a lot of errors.



pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/emf/v1/devices, status: 503, response: Service Unavailable,payload: None
2023-05-01 03:16:20.415 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_outdoor_temperature data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/status, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 109, in get_outdoor_temperature
    return await self._manager.get_outdoor_temperature()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 237, in get_outdoor_temperature
    return mapper.map_outdoor_temp(await self._call_api(self.urls.system_status))
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
    raise ex
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/status, status: 503, response: Service Unavailable,payload: None
2023-05-01 03:16:20.426 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_hvac_status data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/hvacstate/v1/overview, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 157, in get_hvac_status
    return await self._manager.get_hvac_status()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 246, in get_hvac_status
    return mapper.map_hvac_status(await self._call_api(self.urls.hvac))
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
    raise ex
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/hvacstate/v1/overview, status: 503, response: Service Unavailable,payload: None
2023-05-01 03:16:20.517 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_holiday_mode data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/v1/configuration/holidaymode, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 151, in get_holiday_mode
    self._holiday_mode = await self._manager.get_holiday_mode()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 303, in get_holiday_mode
    raw = await self._call_api(self.urls.system_holiday_mode)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
    raise ex
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/v1/configuration/holidaymode, status: 503, response: Service Unavailable,payload: None
2023-05-01 03:17:42.590 ERROR (Thread-5 (_thread_main)) [homeassistant.components.mqtt.client] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2023-05-01 03:17:42.601 WARNING (Thread-5 (_thread_main)) [homeassistant.components.mqtt.client] Disconnected from MQTT server core-mosquitto:1883 (5)
2023-05-01 03:18:23.279 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_dhw data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/dhw, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 128, in get_dhw
    dhw = await self._manager.get_dhw()
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 339, in get_dhw
    dhw = await self._call_api(self.urls.dhws, schema=schemas.DHWS)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
    raise ex
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/dhw, status: 503, response: Service Unavailable,payload: None
2023-05-01 03:18:23.318 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_live_reports data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/livereport/v1, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed
    return await self._fetch_data()

**Comment by xaviergriffon** [comment]
> A short snippet from the debug log. Seems the integration is throwing a lot of errors.
> 
> pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/emf/v1/devices, status: 503, response: Service Unavailable,payload: None 2023-05-01 03:16:20.415 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_outdoor_temperature data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/status, status: 503, response: Service Unavailable,payload: None Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data return await self.update_method() File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed return await self._fetch_data() File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data return await getattr(self.api, self._method)() File "/config/custom_components/multimatic/coordinator.py", line 109, in get_outdoor_temperature return await self._manager.get_outdoor_temperature() File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 237, in get_outdoor_temperature return mapper.map_outdoor_temp(await self._call_api(self.urls.system_status)) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper raise ex File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api response = await self._connector.request(method, url, payload) File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request raise ApiError( pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/status, status: 503, response: Service Unavailable,payload: None 2023-05-01 03:16:20.426 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_hvac_status data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/hvacstate/v1/overview, status: 503, response: Service Unavailable,payload: None Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data return await self.update_method() File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed return await self._fetch_data() File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data return await getattr(self.api, self._method)() File "/config/custom_components/multimatic/coordinator.py", line 157, in get_hvac_status return await self._manager.get_hvac_status() File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 246, in get_hvac_status return mapper.map_hvac_status(await self._call_api(self.urls.hvac)) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper raise ex File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api response = await self._connector.request(method, url, payload) File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request raise ApiError( pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/hvacstate/v1/overview, status: 503, response: Service Unavailable,payload: None 2023-05-01 03:16:20.517 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_holiday_mode data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/v1/configuration/holidaymode, status: 503, response: Service Unavailable,payload: None Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data return await self.update_method() File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed return await self._fetch_data() File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data return await getattr(self.api, self._method)() File "/config/custom_components/multimatic/coordinator.py", line 151, in get_holiday_mode self._holiday_mode = await self._manager.get_holiday_mode() File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 303, in get_holiday_mode raw = await self._call_api(self.urls.system_holiday_mode) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper raise ex File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api response = await self._connector.request(method, url, payload) File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request raise ApiError( pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/v1/configuration/holidaymode, status: 503, response: Service Unavailable,payload: None 2023-05-01 03:17:42.590 ERROR (Thread-5 (_thread_main)) [homeassistant.components.mqtt.client] Unable to connect to the MQTT broker: Connection Refused: not authorised. 2023-05-01 03:17:42.601 WARNING (Thread-5 (_thread_main)) [homeassistant.components.mqtt.client] Disconnected from MQTT server core-mosquitto:1883 (5) 2023-05-01 03:18:23.279 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_dhw data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/dhw, status: 503, response: Service Unavailable,payload: None Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data return await self.update_method() File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed return await self._fetch_data() File "/config/custom_components/multimatic/coordinator.py", line 552, in _fetch_data return await getattr(self.api, self._method)() File "/config/custom_components/multimatic/coordinator.py", line 128, in get_dhw dhw = await self._manager.get_dhw() File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 339, in get_dhw dhw = await self._call_api(self.urls.dhws, schema=schemas.DHWS) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper raise ex File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper return await func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/pymultimatic/systemmanager.py", line 896, in _call_api response = await self._connector.request(method, url, payload) File "/usr/local/lib/python3.10/site-packages/pymultimatic/api/connector.py", line 181, in request raise ApiError( pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/systemcontrol/tli/v1/dhw, status: 503, response: Service Unavailable,payload: None 2023-05-01 03:18:23.318 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_live_reports data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21222700202609620938045772N5/livereport/v1, status: 503, response: Service Unavailable,payload: None Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data return await self.update_method() File "/config/custom_components/multimatic/coordinator.py", line 560, in _fetch_data_if_needed return await self._fetch_data()

Hi
These logs sometimes occur when the Vaillant service no longer accepts communications. But the impact is that the entities become inactive.

When you say that the entities disappear, you are talking about the view of the entities since the integration? Wouldn't you have the "Show unavailable entities" filter unchecked?

**Comment by CommanderROR9** [comment]
"unavailable" entities are shown, but the "clumate" entity simply ceased to exist entirely

**Comment by CommanderROR9** [comment]
Now this is officially weird...
The "climate" entity in the Senso Integration was gone for days now. I just reloaded the integration (not for the first time) and suddenly it's back to 22 entities and the Climate control is back...🤷‍♂️

**Comment by xaviergriffon** [comment]
Strange...
As much as I have the phenomenon of innactivity because of the services but not disappearance.
