### ISSUE TITLE
request_hvac_update failed - vaillant integration unavailable

### ISSUE THREAD

**Issue by h4de5** [thomasgermain/vaillant-component#21]
Hello,

my vaillant integration is offline since over a day - I just checked the logfiles and this is what it says the following:

```

Logger: homeassistant.components.automation.refresh_vaillant_data
Source: custom_components/vaillant/hub.py:63
Integration: Automatisierung (documentation, issues)
First occurred: 9:00:00 (2 occurrences)
Last logged: 9:00:00

Refresh vaillant data: Error executing script. Unexpected error for call_service at pos 1: Expecting value: line 1 column 1 (char 0)
While executing automation automation.refresh_vaillant_data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 206, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/vaillant/service.py", line 155, in request_hvac_update
    await self._hub.request_hvac_update()
  File "/config/custom_components/vaillant/hub.py", line 63, in request_hvac_update
    await self._manager.request_hvac_update()
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 546, in request_hvac_update
    state = mapper.map_hvac_sync_state(await self._call_api(urls.hvac))
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 582, in _call_api
    return await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/api/connector.py", line 169, in request
    await resp.json(content_type=None)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


and 


Logger: custom_components.vaillant.hub
Source: custom_components/vaillant/hub.py:66
Integration: Vaillant (documentation)
First occurred: 0:00:00 (2 occurrences)
Last logged: 8:00:00
request_hvac_update is done too often
```

The mobile app seems to be able to connect just fine - so the device should be ok. I have an automation that does the `request_hvac_update` every hour just as recommended - which I reduced now to every 3 hours in case.

My guess is, that it does the refresh on every hass startup - and because I restart it during developing quite often, it somehow banned me :(

Did you ever encounter such behaviour? Did you solve it maybe?

**Comment by thomasgermain** [comment]
Hello,

so first what do you mean by `the integration is offline` ? You don't have any new data coming in ? If it's the case, do you have any other errors ? Because the integration is refreshing the data every 2 minutes, so if you don't have any new data for 1 day, you should have plenty of errors.

 I have something in my todo list to fix the `JSONDecodeError`, sometimes, it seems the API doesn't return json. I'm still wondering how I can do that.

You could have the `request_hvac_update is done too often` if you open the app and just after the HA integration is also calling the `request_hvac_update `. So if you only had the warning once, I would recommend to keep it every 1h.

Yes, the integration is getting data at HA starting (like any other integration actually). 

By the way, if you are developing, you should use HA inside docker https://www.home-assistant.io/docs/installation/docker/. I'm suing that (so my "production" HA is actually never restart expect on electricity failure or update).

**Comment by h4de5** [comment]
after restart - thats the very first message:

```
2020-10-06 22:16:43 ERROR (MainThread) [custom_components.vaillant.hub] Unable to fetch data from vaillant, API says: {'errorCode': 'FACILITY_NOT_ONLINE'}, status: 409
Traceback (most recent call last):
  File "/config/custom_components/vaillant/hub.py", line 75, in _update_system
    self.system = await self._manager.get_system()
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 83, in get_system
    full_system = await full_system_req
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 582, in _call_api
    return await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/api/connector.py", line 170, in request
    raise ApiError('Cannot ' + method + ' ' + url, response=resp,
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/xxxxx/systemcontrol/v1
```

and thats it - in hass the all entities just read "unavailable".
I also just checked the logs and the automation for `request_hvac_update` does not get triggered directly after each restart - so my worry was arbitrary.


/edit: and *of course* - while writing this and restarting home-assistant once again - everything went back to normal.
maybe vaillant just put me on a temporary ban and the update once every hour somehow prolonged it .. or I don't know ..

**Comment by thomasgermain** [comment]
yeah, of course 😛 (it only happens to me).

Actually, the vaillant API is quite unstable, I often receive an empty message, or an error "REPORT_DOES_NOT_EXIST", "FACILITY_NOT_ONLINE" or connection timeout (specially during the night). This is why I put extra effort for the integration to be able to recover from these errors, so you don't have to restart HA.

I don't think there is some kind of ban, are you using a dedicated user for HA ?

**Comment by h4de5** [comment]
I thought so. yes - the HA integration uses a different account than my mobile phone - which I use anyways just to check if the API is really offline or my HA setup somehow messed up again ;)

still strange - i restartet HA pretty often yesterday, but at least between 10pm and just before I didn't any data in the log.

but again thanks for the clearification.
