### ISSUE TITLE
Error "Unexpected error fetching multimatic_facility_detail data: list index out of range"

### ISSUE THREAD

**Issue by kverbeke** [thomasgermain/vaillant-component#213]
Hi,
I've been succesfully using your Multimatic integration for several months. Yesterday, I noticed that the integration did show only 2 entities (quick mode and holiday). I checked the Multimatic app on my phone to confirm the problem is not on the Vaillant side.
In the system log, I found the error message in the title.

Below is the full detail of the error.
There haven't been any changes on my setup or configuration. My HASS system is fully up to date.

Can you please advise what I can do.

Thanks and best regards.

Kristiaan
---------------------------------------------------------------------------

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:97
Integration: Multimatic (documentation, issues)
First occurred: 20:02:05 (1 occurrences)
Last logged: 20:02:05

Unexpected error fetching multimatic_facility_detail data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 566, in _first_fetch_data
    result = await self._fetch_data()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 554, in _fetch_data
    return await getattr(self.api, self._method)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 97, in get_facility_detail
    detail = await self._manager.get_facility_detail(self.serial)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 261, in get_facility_detail
    return mapper.map_facility_detail(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 273, in map_facility_detail
    facility = [
               ^
IndexError: list index out of range

-----------------------------------------------------------------------------------------------------------------------------------
Another error, occuring every 2 minutes (=update frequency), and I guess it is the consequence of the above issue, is:
Unexpected error fetching multimatic_quick_mode data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/##MYSERIALNUMBERr##/systemcontrol/v1/configuration/quickmode, status: 400, response: {"errorCode":"INVALID_PARAMS"},payload: None

**Comment by 85Kid** [comment]
Hi there, I have a similar error. I´m using a dedicated user for Home Assistant. 
_____________

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:158
Integration: Multimatic (documentation, issues)
First occurred: 03:01:23 (10 occurrences)
Last logged: 03:19:50

Unexpected error fetching multimatic_hvac_status data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/2122290020260962093XXXXXXXXX/hvacstate/v1/overview, status: 503, response: Service Unavailable,payload: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 562, in _fetch_data_if_needed
    return await self._fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 554, in _fetch_data
    return await getattr(self.api, self._method)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 158, in get_hvac_status
    return await self._manager.get_hvac_status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 252, in get_hvac_status
    return mapper.map_hvac_status(await self._call_api(self.urls.hvac))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 84, in wrapper
    raise ex
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 902, in _call_api
    response = await self._connector.request(method, url, payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/api/connector.py", line 181, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/2122290020260962093XXXXXXXXX/hvacstate/v1/overview, status: 503, response: Service Unavailable,payload: None

**Comment by lecocqe** [comment]
Hello, vaillant server was not recheable this night (on my side) from 3:00 to 4:54
![image](https://github.com/thomasgermain/vaillant-component/assets/18657222/1941d3b4-f5e8-4ad8-ac9a-7524fd5a5390)

no problem with integration i think

**Comment by kverbeke** [comment]
Update: 
- I uninstalled and reinstalled the integration, with the same results.
- The unavailability of the Vaillant server as mentioned by lecocqe is certainly not the reason for the issue I logged.
- I'm not sure that the reaction by 85Kid above is the same issue. 
Hopefully Thomas Germain can clarify the issue and indicate how to resolve.

**Comment by thomasgermain** [comment]
Hello @kverbeke, did you try to reload the integration ?
Do you have any other errors ? The error you mentioned only affect few entities, so you should definitely have other entities if this is the only error you have.

The error means there is no installation for your serial number. Did you provide your serial number or did you let the integration find it ?

**Comment by 85Kid** [comment]
@lecocqe having the same error today. 
![image](https://github.com/thomasgermain/vaillant-component/assets/138862797/7b1883f9-c469-4361-93fc-32c1719d68c7)

You think it was down again?

**Comment by kverbeke** [comment]
@thomasgermain : 
I've now readded the hub WITHOUT filling in the serial number, and this works correctly. 
Thanks for your support!
