### ISSUE TITLE
Only two entities

### ISSUE THREAD

**Issue by jacoqq** [thomasgermain/vaillant-component#216]
Hi,
Can someone please tell me what I need to do if I want to see more than two entities from MULTIMATIC. integration I have VR920 and only I can see is: Multimatic holiday binary_sensor.multimatic_holiday and Multimatic quick mode binary_sensor.multimatic_quick_mode. There is a in/out temp, preasure, etc on my app, but it doesn't show in HA. I found something in debug, but I don't know what it mean. 
```
2023-08-11 12:09:26.360 ERROR (MainThread) [custom_components.multimatic.coordinator] Unexpected error fetching multimatic_facility_detail data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 566, in _first_fetch_data
    result = await self._fetch_data()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 554, in _fetch_data
    return await getattr(self.api, self._method)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 97, in get_facility_detail
    detail = await self._manager.get_facility_detail(self.serial)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 261, in get_facility_detail
    return mapper.map_facility_detail(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 273, in map_facility_detail
    facility = [
               ^
``` 
Please help.

**Comment by thomasgermain** [comment]
Hello, did you specify your serial number during the setup ?

If yes, trying to setup the integration without it

**Comment by jacoqq** [comment]
That is what I'm talking about :) Thank You so much thomasgermain
