### ISSUE TITLE
Error while updating sensor

### ISSUE THREAD

**Issue by thomasgermain** [thomasgermain/vaillant-component#22]
2020-10-28 23:07:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.vaillant_waterpressuresensor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 469, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/vaillant/entities.py", line 47, in async_update
    await self.vaillant_update()
  File "/config/custom_components/vaillant/sensor.py", line 92, in vaillant_update
    self.report = self._find_report()
  File "/config/custom_components/vaillant/sensor.py", line 96, in _find_report
    if self.report.id == report.id:

**Comment by thomasgermain** [comment]
fixed with 1.5.0b1
