### ISSUE TITLE
Climate entity is unavailable

### ISSUE THREAD

**Issue by rhgiter** [thomasgermain/vaillant-component#227]
Climate entity is unavailable

I use sensoapp

all other entity is working.

what to do ?

![image](https://github.com/thomasgermain/vaillant-component/assets/61065752/789154f7-f569-4ef2-b618-234efd809714)

It happend when I turned on my heating pump in Auto mode.

![image](https://github.com/thomasgermain/vaillant-component/assets/61065752/d74a7a53-b809-4619-b67e-fa28faa27c02)

**Comment by thomasgermain** [comment]
Any error in the logs ?

**Comment by rhgiter** [comment]
my log is here :

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:105
Integration: Multimatic (documentation, issues)
First occurred: 09.57.00 (1 occurrences)
Last logged: 09.57.00

Unexpected error fetching multimatic_zones data: cannot access local variable 'time_program_day' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 566, in _first_fetch_data
    result = await self._fetch_data()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 554, in _fetch_data
    return await getattr(self.api, self._method)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/coordinator.py", line 105, in get_zones
    return await self._manager.get_zones()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 381, in get_zones
    return mapper.map_zones(rooms)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 289, in map_zones
    return _map_zones(json.get("body", []))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 301, in _map_zones
    zone = map_zone(raw_zone)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 338, in map_zone
    func = _map_function(raw_heating, "setting", rbr, quick_veto is not None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 421, in _map_function
    time_program = map_time_program(raw.get("timeprogram"), tp_key)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 215, in map_time_program
    result[day_of_week] = map_time_program_day(raw_time_program.get(day_of_week), key)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/model/mapper.py", line 249, in map_time_program_day
    return time_program_day
           ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'time_program_day' where it is not associated with a value

**Comment by rhgiter** [comment]
some how it worked again- Strange?!?!

![image](https://github.com/thomasgermain/vaillant-component/assets/61065752/6643a0c0-a5d5-411b-950c-518a1a2cf3fa)

**Comment by thomasgermain** [comment]
No that strange actually, the vailant API is quite unstable and sometimes it gives partial response or even not response at all, this is why entities became unavailable
