### ISSUE TITLE
Empty energy metrics and errors in logs after upgrading HA 

### ISSUE THREAD

**Issue by vmorarian** [thomasgermain/vaillant-component#239]
Setup:

Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

Latest Multimatic integration

At some point (few days ago probably) it stopped to populate energy related metrics. Checked logs and noticed

```
2023-10-16 12:56:16.681 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform multimatic
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
attr.update(self.state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 345, in state_attributes
if hvac_action := self.hvac_action:
^^^^^^^^^^^^^^^^
File "/config/custom_components/multimatic/climate.py", line 674, in hvac_action
or self.current_temperature < self.target_temperature
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'NoneType'
```

Looks like stopped to work ~ 14Oct

<img width="1048" alt="image" src="https://github.com/thomasgermain/vaillant-component/assets/328763/91c46cf0-04a1-40b3-9639-0e71ce23d987">

**Comment by thomasgermain** [comment]
What do you mean by latest version 😋, the beta one or the 1.16.2 ? 

Is there any other logs ? Sounds like the one you provide is not related with energy sensors.

Are energy values in the mobile app correct ?

Did you notice any climate entity which is unavailable?

**Comment by thomasgermain** [comment]
Thanks for your answer.

But I'm still interested in the error log you provided 😁. 
Do you have any water heater, if yes what kind ? It sounds like the integration cannot find the target temperature for it

**Comment by vmorarian** [comment]
Just got response from installer. It looks like that same issue has affected multiple installations because installer got calls from other clients with same question.
All other stuff (like changing temperature of zone, etc) seems like fully functional.

Logs after restarting HA:
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 18:46:45 (1 occurrences)
Last logged: 18:46:45

Error adding entities for domain climate with platform multimatic
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 345, in state_attributes
    if hvac_action := self.hvac_action:
                      ^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/climate.py", line 674, in hvac_action
    or self.current_temperature < self.target_temperature
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'NoneType'
```

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:367
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 18:46:45 (1 occurrences)
Last logged: 18:46:45

Error while setting up multimatic platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 345, in state_attributes
    if hvac_action := self.hvac_action:
                      ^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/climate.py", line 674, in hvac_action
    or self.current_temperature < self.target_temperature
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'NoneType'
```

```
Logger: homeassistant
Source: custom_components/multimatic/climate.py:674
Integration: Multimatic ([documentation](https://github.com/thomasgermain/vaillant-component), [issues](https://github.com/thomasgermain/vaillant-component/issues))
First occurred: 18:47:45 (71 occurrences)
Last logged: 19:57:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 345, in state_attributes
    if hvac_action := self.hvac_action:
                      ^^^^^^^^^^^^^^^^
  File "/config/custom_components/multimatic/climate.py", line 674, in hvac_action
    or self.current_temperature < self.target_temperature
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'NoneType'
```

Setup:
<img width="907" alt="image" src="https://github.com/thomasgermain/vaillant-component/assets/328763/034433f9-723f-4a64-93f4-ec9721029ffa">

**Comment by thomasgermain** [comment]
What kind of water heater do you have ? 
Can you set a timeprogram for it ?
Is it a direct heater or do you have a tank ?

**Comment by vmorarian** [comment]
- ecoTEC Plus is heating water
- eloBlock is kinda backup now
- yeah, I have tank
- circulation of hot water has timeprogram 
- heating water also has timeprogram

**Comment by thomasgermain** [comment]
Thanks for your response.

Could you show which climate entities are created by the integration ? And also, can you show me which climate entity is unavailable ?
