### ISSUE TITLE
set temperature status 400 error

### ISSUE THREAD

**Issue by ttuuxxeerr** [thomasgermain/vaillant-component#249]
Hi there,

The plugin is working fine getting the information however if I try to change the temperature I am getting the following error: 

```
Logger: homeassistant.components.websocket_api.http.connection Source: components/websocket_api/commands.py:230  Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))  First occurred: 19:06:33 (1 occurrences)  Last logged: 19:06:33
[547932998208] Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21231900edited48N8/rbr/v1/rooms/1/configuration/quickVeto, status: 400, response: {"errorCode":"INVALID_PARAMS"},payload: {'temperatureSetpoint': 19.0, 'duration': 3}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 632, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/multimatic/climate.py", line 370, in async_set_temperature
    await self.coordinator.api.set_room_target_temperature(
  File "/config/custom_components/multimatic/coordinator.py", line 236, in set_room_target_temperature
    await self._manager.set_room_quick_veto(room.id, qveto)
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 587, in set_room_quick_veto
    await self._call_api(self.urls.room_quick_veto, params={"id": room_id}, payload=payload)
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 80, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 902, in _call_api
    response = await self._connector.request(method, url, payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/api/connector.py", line 181, in request
    raise ApiError(
pymultimatic.api.error.ApiError: Cannot put https://smart.vaillant.com/mobile/api/v4/facilities/21231900edited48N8/rbr/v1/rooms/1/configuration/quickVeto, status: 400, response: {"errorCode":"INVALID_PARAMS"},payload: {'temperatureSetpoint': 19.0, 'duration': 3}
```

I am using:

- Module internet VR921 Vaillant
- Thermostat Vaillant sensocomfort VRC 720F
- ambisense VR50

Thanks for in advance for any tip or help.

**Comment by ttuuxxeerr** [comment]
Hi,

Any idea what could be the issue?

Regards
