### ISSUE TITLE
Unable to set_ventilation_day_level

### ISSUE THREAD

**Issue by Waschbeton** [thomasgermain/vaillant-component#261]
i'm having troubles getting set_ventilation_day_level to work.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 831, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/multimatic/fan.py", line 145, in set_ventilation_day_level
    await self.coordinator.api.set_fan_day_level(self, kwargs.get(ATTR_LEVEL))
  File "/config/custom_components/multimatic/coordinator.py", line 415, in set_fan_day_level
    await self._manager.set_ventilation_day_level(entity.component.id, level)
  File "/usr/local/lib/python3.11/site-packages/pymultimatic/systemmanager.py", line 809, in set_ventilation_day_level
    payload=self.payloads.ventilation_day_level(level),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pymultimatic.api.payloads' has no attribute 'ventilation_day_level'
```

**Comment by lennartjung** [comment]
+1 I've got the same problem

**Comment by VaillantHassIo** [comment]
same issue here. sounds like they changes something in their API
