### ISSUE TITLE
custom_components/multimatic/sensor.py:103 AttributeError: 'NoneType' object has no attribute 'unit'

### ISSUE THREAD

**Issue by Wiggum127** [thomasgermain/vaillant-component#56]
Have been getting this error for some time now. Running multimatic component v1.6.0, HA Container v2021.5.0

Logger: homeassistant
Source: custom_components/multimatic/sensor.py:103
Integration: Multimatic (documentation, issues)
First occurred: 23 mei 2021 19:23:57 (66 occurrences)
Last logged: 16:32:20

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 127, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 259, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in _async_write_ha_state
    unit_of_measurement = self.unit_of_measurement
  File "/config/custom_components/multimatic/sensor.py", line 103, in unit_of_measurement
    return self.report.unit
AttributeError: 'NoneType' object has no attribute 'unit'

**Comment by pepsonEL** [comment]
I also have a problem the sam.... and still no read infor from multimatic... some time read ok but sometime no read.

`Logger: homeassistant
Source: custom_components/multimatic/sensor.py:103
Integration: Multimatic (documentation, issues)
First occurred: 25 maja 2021, 17:46:10 (147 occurrences)
Last logged: 21:49:14

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 127, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 259, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 378, in _async_write_ha_state
    unit_of_measurement = self.unit_of_measurement
  File "/config/custom_components/multimatic/sensor.py", line 103, in unit_of_measurement
    return self.report.unit
AttributeError: 'NoneType' object has no attribute 'unit'
`

**Comment by lecocqe** [comment]
same behaviour here.

**Comment by thomasgermain** [comment]
Just released 1.7.0b0 see https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b0
It *should* fix the issue (or at least reduce it). You can see it through HACS, if you enable beta
(I tested it for 2 days and I didn't have any error, expect around 3:30).

**Comment by Wiggum127** [comment]
Upgraded to latest and greatest of HA DC (v2021.6.2) and multimatic (v1.7.0b0 via git clone) in the custom_components dir.

It resulted in all multimatic related entities being duplicated. I removed the duplicate multimatic entities which were not working, resulting in a set the full set of entities being operational.

Will keep an eye on the logs and revert back in case something pops up.

I enabled HACS beta versions but did not find any trace of multimatic or vaillant.

**Comment by thomasgermain** [comment]
@Wiggum127 you can check 1.7.0b1, it should the issue

**Comment by Wiggum127** [comment]
Upgraded to 1.7.0b1. Will keep an eye on things.

**Comment by thomasgermain** [comment]
Do you still have the issue ?

**Comment by Wiggum127** [comment]
I did not find the same error back for a couple of days running 1.7.0b3. I'm getting a lot of connection errors with the gateway from different .py files, but not this error.

**Comment by thomasgermain** [comment]
Ok se closing it, feel free to open a new issue if you have still problem
