### ISSUE TITLE
custom_components/multimatic/sensor.py:127 - AttributeError: 'NoneType' object has no attribute 'unit

### ISSUE THREAD

**Issue by Wiggum127** [thomasgermain/vaillant-component#64]
Running HA DC 2021.6.2, python 3.8.9, multimatic integration custom component v1.7.0b

`Logger: homeassistant
Source: custom_components/multimatic/sensor.py:127
Integration: Multimatic (documentation, issues)
First occurred: 21 juni 2021 15:46:34 (1 occurrences)
Last logged: 21 juni 2021 15:46:34

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in _async_write_ha_state
    device_class = self.device_class
  File "/config/custom_components/multimatic/sensor.py", line 127, in device_class
    return UNIT_TO_DEVICE_CLASS.get(self.report.unit, None)
AttributeError: 'NoneType' object has no attribute 'unit'
`

**Comment by thomasgermain** [comment]
#56

**Comment by Wiggum127** [comment]
Sorry for the duplicate. Searched for it but didn't an obvious match with an existing issue.
