### ISSUE TITLE
custom_components/multimatic/coordinator.py:106 - pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities

### ISSUE THREAD

**Issue by Wiggum127** [thomasgermain/vaillant-component#65]
Running HA DC 2021.6.2, python 3.8.9, multimatic integration custom component v1.7.0b

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:106
Integration: Multimatic (documentation, issues)
First occurred: 01:34:26 (2 occurrences)
Last logged: 01:51:27

Unexpected error fetching multimatic data: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 106, in _fetch_data
    system = await self._manager.get_system()
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 127, in get_system
    facilities, full_system, live_report, hvac_state, gateway = await asyncio.gather(
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 47, in wrapper
    raise ex
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 43, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/systemmanager.py", line 713, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.8/site-packages/pymultimatic/api/connector.py", line 174, in request
    raise ApiError('Cannot ' + method + ' ' + url, response=await resp.text(),
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities

**Comment by thomasgermain** [comment]
You should have another log at the same time approx.
I also have this one and I receive a "server disconnected"

**Comment by thomasgermain** [comment]
It should be solve with https://github.com/thomasgermain/vaillant-component/releases/tag/1.7.0b4, please let me know if you still have the issue

**Comment by Wiggum127** [comment]
Just upgraded to 1.7.0b4. Will keep you posted.

**Comment by thomasgermain** [comment]
version 1.7.0 is out and I'm doing some cleaning, please open an new issue if you still have trouble.
