### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by hoebanx** [thomasgermain/vaillant-component#78]
Hello hello,
Since the (super nice) integration changes from vaillant to multimatic I have stability issues.
I have to uninstall, reinstall reinsert my credentials (user, pass and really long serial number) and reallocate my devices to the right rooms.
I tried the ‘reinstall’ option in hacs but it does not work, I really have to remove and reinstall.
I’m using last ha version with a dedicated multimatic user.
Before going more into details, did you noticed the same bewavior with other users?
I’m using hotwater_boost and a lot of ambisense valves.
It was really stable before

See details bellow.

have a nice day,
Ludovic

core-2021.7.1
Supervisor 2021.06.8
Home Assistant OS 6.1
Multimatic version 1.6.2. I saw version 1.7.0 was released 11h ago? I'll try.
![fbadd39c8ee3558166063ee69ecd6cb73851830e](https://user-images.githubusercontent.com/77239440/125209243-d4057a80-e297-11eb-8fbe-eb8022729dd3.jpeg)

2021-07-11 08:20:01 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration multimatic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-11 08:22:27 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Multimatic for multimatic
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
transport, protocol = await self._create_connection_transport(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
await waiter
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 918, in write
n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/multimatic/__init__.py", line 25, in async_setup_entry
await api.authenticate()
File "/config/custom_components/multimatic/hub.py", line 79, in authenticate
return await self._manager.login(True)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 60, in login
return await self._connector.login(force_login)
File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 67, in login
token = await self._token()
File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 106, in _token
token_res = await self._session.post(url=urls.new_token(),
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host smart.vaillant.com:443 ssl:default [Connection reset by peer]
2021-07-11 08:23:08 ERROR (SyncWorker_3) [homeassistant.components.command_line] Command failed: cat /sys/class/thermal/thermal_zone0/temp

**Comment by thomasgermain** [comment]
You should definitely try the 1.7.0 (have a look at the release note).

Underlying error is `aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host smart.vaillant.com:443 ssl:default [Connection reset by peer]`, it means `smart.vaillant.com` reset the connection, this is a quite common error in IT world.

As I said on HA forum, you should try "reload" the integration, it will do the same as when HA is starting

**Comment by hoebanx** [comment]
Hello,
I updated, it is working right now (without having to re-enter the login).
I'll keep you posted.
Have a nice day

Le lun. 12 juil. 2021 à 12:33, Thomas Germain ***@***.***> a
écrit :

**Comment by thomasgermain** [comment]
I'll close this one, since it seems to work for you :)

**Comment by hoebanx** [comment]
Thanks a lot!

Le ven. 16 juil. 2021 à 17:42, Thomas Germain ***@***.***> a
écrit :
