### ISSUE TITLE
Unexpected error fetching multimatic_dhw data: Expecting value: line 1 column 1 (char 0) - coordinator.py:118

### ISSUE THREAD

**Issue by Wiggum127** [thomasgermain/vaillant-component#82]
Running HA Docker 2021.7.2, multimatic v1.7.0

I'm getting similar errors (like the log below) in coordinator.py:94, 99, 118, 130 and 147

Logger: custom_components.multimatic.coordinator
Source: custom_components/multimatic/coordinator.py:118
Integration: Multimatic (documentation, issues)
First occurred: 21 juli 2021 19:49:32 (4 occurrences)
Last logged: 20:55:33

Unexpected error fetching multimatic_dhw data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/multimatic/coordinator.py", line 503, in _fetch_data_if_needed
    return await self._fetch_data()
  File "/config/custom_components/multimatic/coordinator.py", line 496, in _fetch_data
    return await getattr(self.api, self._method)()
  File "/config/custom_components/multimatic/coordinator.py", line 118, in get_dhw
    dhw = await self._manager.get_dhw()
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 42, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 313, in get_dhw
    dhw = await self._call_api(urls.dhws, schema=schemas.DHWS)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 79, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/systemmanager.py", line 815, in _call_api
    response = await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.9/site-packages/pymultimatic/api/connector.py", line 171, in request
    return await resp.json(content_type=None)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1113, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by thomasgermain** [comment]
As usual :/ wrong responses coming from vaillant API. 

I also have same error, but it only appears like 5 times yesterday. I can't do anything about that
